### ISSUE TITLE
Copyright warning

### ISSUE THREAD

**Issue by holao09** [quocthinhvo/kodeweb#1]
Pascal is Pascal.
Clone and rename without credit is unfair developer.
Please read the term and try to understand it.

**Comment by quocthinhvo** [comment]
> Pascal is Pascal.
> Clone and rename without credit is unfair developer.
> Please read the term and try to understand it.

En chào bác. Em thấy tên bác là đoán bác là người Việt nên em xin phép dùng tiếng Việt để có thể thể hiện trọn vẹn nội dung mà em muốn trình bày.

Điều thứ nhất mọi người đã hiểu lầm về KodeLang. Trong bài viết trên Viblo em có ghi là Kode có thể có ngôn ngữ riêng là KodeLang và em cũng ghi rõ nó kế thừa từ Pascal. Em còn mở ngoặc ghi đậm rằng đang trong quá trình nghiên cứu.
==>Điều này khẳng định Kode là một dự án cho Pascal. KodeLang chỉ là cái trong tương lai có thể có

Thứ 2 em sẽ trình bày về vấn đề bản quyền và giấy phép. Kode có kế thừa từ những dự án "đàn anh" và hâuf hết lấy giấy phép GLP. Kode kế thừa chủ đạo từ FPC và Lazarus (chính xác hơn là LCL).

Thứ 3: tất cả những nguồn em kế thừa điều có giấy phép mã nguồn mở và em tham khảo rất kĩ mới sử dụng. 

Thứ 4: em tôn trọng mã nguồn của người khác. Trong repo của KodePas em để rõ ràng các tệp bản quyền của LCL. Các đoạn comment bản quyền trong từng tệp của LCL đều được em giữ nguyên và thực hiện đúng theo giấy phép. Ngay tại trang chủ của Kode em có để rõ ràng dòng "Kode is free and open source platform from FPC and LCL project
for building powerful applications." 

Thứ 5: em không chỉ kế thừa mà còn có sự cải tiến, phát triển. Em viết thêm nhiều lib và widget cho LCL. Và hơn hết em thêm tính năng phát triển Web và Hybrid cho Kode (điều mà Lazarus còn hạn chế)

Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này

Thứ 7: Trong bài viết trên Viblo em có ghi rất rõ sẽ trình bày cụ thể cấu trúc từng phần Kode trong một bài viết mới.

Thứ 8: Kode vẫn lấy giấy phép GPL 3.0. 

==> Đó là tất cả những luận điểm để chứng minh Kode không vi phạm bản quyền và các giấy phép mã nguồn mở. Do mọi người có thể chưa hiểu rõ về Kode. Trong một vài viết tới em sẽ trình bày rõ hơn nữa. 

Thân ái !

**Comment by quocthinhvo** [comment]
> Pascal is Pascal.
> Clone and rename without credit is unfair developer.
> Please read the term and try to understand it.

Mục tiêu của dự án là đóng góp cho chính cộng đồng Việt Nam. Em không được lợi nhuận tiền bạc gì từ dự án này cả. Tất cả là miễn phí. Em mong muốn cộng đồng ủng hộ mình và cải tiện Kode. Có thể do bài viết trên Viblo em chưa rõ ràng dẫn đến những hiểu lầm không đáng có.

Em phát triển Kode cũng như Ionic vậy. Thêm component và viết nhiều lib, bổ sung nhiều tài liệu và mở rộng tính năng. Ionic cũng kế thừa từ Cordova còn Kode thì từ Lazarus và FPC. Em giũ tốt các giấy phép, ghi rõ bản quyền.

Nếu những vấn đề em làm có sai sót, em xin nhận mọi trách nhiệm.
Tất cả vì cộng đồng của Việt Nam.

Thân ái!

**Comment by quocthinhvo** [comment]
> Pascal is Pascal.
> Clone and rename without credit is unfair developer.
> Please read the term and try to understand it.

Mong nhận được phản hồi từ bác.

**Comment by quocthinhvo** [comment]
> Pascal is Pascal.
> Clone and rename without credit is unfair developer.
> Please read the term and try to understand it.

Một lần nữa em xin khẳng định Kode không hề vi phạm bản quyền hoặc giấy phép. Tất cả đều đúng và hợp lệ.
Nếu Kode phát triển thì Lazarus, FPC và Pascal sẽ phát triển. Pascal, Lazarus và FPC phát triển thì Kode cũng phát triển.
Và hơn hết là cộng đồng của chúng ta lớn mạnh.

Trân trọng!

**Comment by quocthinhvo** [comment]
> Pascal is Pascal.
> Clone and rename without credit is unfair developer.
> Please read the term and try to understand it.

Cũng xin nhấn mạnh với bác là Kode sẽ chú trọng phát triển cho mảng Web và Hybrid. Còn Lazarus và Delphi đã quá mạnh ở Native rồi nên Kode sẽ đi nhánh còn lại. Mọi người sẽ thấy điểm khác biệt của Kode (có khác biệt thì em mới tuyên bố làm một nhánh riêng chứ)

**Comment by quocthinhvo** [comment]
@holao09 em đứng đây chờ bác từ sáng giờ

**Comment by holao09** [comment]
Xin lỗi @quocthinhvo ,
Mình đi làm nên trong giờ ít khi để ý.
Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.

1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.

**Comment by quocthinhvo** [comment]
> Xin lỗi @quocthinhvo ,
> Mình đi làm nên trong giờ ít khi để ý.
> Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> 
> 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.

Dạ em hiểu ý của anh.
1. Em cũng đang cống hiến cho cộng đồng
2. Kode cũng GPL 3.0 ạ
3. Do em đang phát triển nên ít commit ạ
4. Em sẽ đề phòng ạ.

Còn vấn đề "nổ" là do em lần đầu công bố dự án nên háo hức và muốn thu hút mọi người tham gia cùng nên hơi lố tí. Em sẽ chỉnh sửa lại văn phong của mình.
@holao09 em cảm ơn anh ạ

**Comment by quocthinhvo** [comment]
> Xin lỗi @quocthinhvo ,
> Mình đi làm nên trong giờ ít khi để ý.
> Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> 
> 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.

anh có thể nói rõ hơn về mục số 3 không ạ. Để em hiệu chỉnh phù hợp @holao09

**Comment by holao09** [comment]
> 
> 
> > Xin lỗi @quocthinhvo ,
> > Mình đi làm nên trong giờ ít khi để ý.
> > Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> > Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> > Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> > 
> > 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> > 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> > 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> > 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.
> 
> anh có thể nói rõ hơn về mục số 3 không ạ. Để em hiệu chỉnh phù hợp @holao09

Mô tả cho dễ hiểu : https://github.com/CyanogenMod/android
CyanogenMod là 1 hệ điều hành họ Android.
Nó giống như android, base trên rất nhiều gói.
Họ phát triển các gói đó theo hướng của họ : fork về rồi update.
Sau đó họ tạo 1 project lấy source từ các repo fork đó về build và ghép thành sản phẩm.
Hãy xem các project họ làm. Cái nào cũng chuẩn chỉ cả.
Đầu tiên hãy fork Lararus và Pascal về.
Update nó ---> tạo project lắp ghép 2 source đó ---> kode.
Đấy là cách cậu có thể tham kháo, có thể còn nhiều cách khác nữa.

**Comment by quocthinhvo** [comment]
> > > Xin lỗi @quocthinhvo ,
> > > Mình đi làm nên trong giờ ít khi để ý.
> > > Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> > > Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> > > Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> > > 
> > > 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> > > 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> > > 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> > > 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.
> > 
> > 
> > anh có thể nói rõ hơn về mục số 3 không ạ. Để em hiệu chỉnh phù hợp @holao09
> 
> Mô tả cho dễ hiểu : https://github.com/CyanogenMod/android
> CyanogenMod là 1 hệ điều hành họ Android.
> Nó giống như android, base trên rất nhiều gói.
> Họ phát triển các gói đó theo hướng của họ : fork về rồi update.
> Sau đó họ tạo 1 project lấy source từ các repo fork đó về build và ghép thành sản phẩm.
> Hãy xem các project họ làm. Cái nào cũng chuẩn chỉ cả.
> Đầu tiên hãy fork Lararus và Pascal về.
> Update nó ---> tạo project lắp ghép 2 source đó ---> kode.
> Đấy là cách cậu có thể tham kháo, có thể còn nhiều cách khác nữa.

em cảm ơn anh và sẽ thực hiện ngay ạ

**Comment by quocthinhvo** [comment]
> > > Xin lỗi @quocthinhvo ,
> > > Mình đi làm nên trong giờ ít khi để ý.
> > > Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> > > Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> > > Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> > > 
> > > 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> > > 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> > > 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> > > 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.
> > 
> > 
> > anh có thể nói rõ hơn về mục số 3 không ạ. Để em hiệu chỉnh phù hợp @holao09
> 
> Mô tả cho dễ hiểu : https://github.com/CyanogenMod/android
> CyanogenMod là 1 hệ điều hành họ Android.
> Nó giống như android, base trên rất nhiều gói.
> Họ phát triển các gói đó theo hướng của họ : fork về rồi update.
> Sau đó họ tạo 1 project lấy source từ các repo fork đó về build và ghép thành sản phẩm.
> Hãy xem các project họ làm. Cái nào cũng chuẩn chỉ cả.
> Đầu tiên hãy fork Lararus và Pascal về.
> Update nó ---> tạo project lắp ghép 2 source đó ---> kode.
> Đấy là cách cậu có thể tham kháo, có thể còn nhiều cách khác nữa.

em làm theo cách này có thể tránh được trường hợp 4 không ạ

**Comment by quocthinhvo** [comment]
> > > Xin lỗi @quocthinhvo ,
> > > Mình đi làm nên trong giờ ít khi để ý.
> > > Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> > > Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> > > Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> > > 
> > > 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> > > 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> > > 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> > > 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.
> > 
> > 
> > anh có thể nói rõ hơn về mục số 3 không ạ. Để em hiệu chỉnh phù hợp @holao09
> 
> Mô tả cho dễ hiểu : https://github.com/CyanogenMod/android
> CyanogenMod là 1 hệ điều hành họ Android.
> Nó giống như android, base trên rất nhiều gói.
> Họ phát triển các gói đó theo hướng của họ : fork về rồi update.
> Sau đó họ tạo 1 project lấy source từ các repo fork đó về build và ghép thành sản phẩm.
> Hãy xem các project họ làm. Cái nào cũng chuẩn chỉ cả.
> Đầu tiên hãy fork Lararus và Pascal về.
> Update nó ---> tạo project lắp ghép 2 source đó ---> kode.
> Đấy là cách cậu có thể tham kháo, có thể còn nhiều cách khác nữa.

trường hợp 4 theo anh nhắc thì theo cách này có né được không ạ @holao09

**Comment by tvc12** [comment]
> Xin lỗi @quocthinhvo ,
> Mình đi làm nên trong giờ ít khi để ý.
> Một trong những cái sai lớn nhất ở bạn đấy là "nổ"
> Chuyện nổ ở đâu cũng thế nó sẽ kéo theo hậu quả là sự phản ứng trái chiều.
> Ở góc độ của tôi, cậu là 1 **tài năng** nhưng cậu chưa hiểu luật chơi với phần mềm và chưa chơi đúng cách.
> 
> 1. Luật fair-use : Dùng đồ của cộng đồng thì phải cống hiến cho cộng đồng. Cái này là có vay có trả. Không ai thiệt cả.
> 2. Giấy phép và bản quyền: GPL là 1 giấy phép khá cứng. Luật đầu tiên của nó là mọi phần mềm phái sinh từ giấy phép GPL đều phải dùng giấy phép GPL. Kết hợp các phần mềm thì phải để ý các loại giấy phép, khi kết hợp phải đảm bảo không vi phạm.
> 3. Về cách xây dựng phần mềm, vì cậu không opensource toàn bộ code Kode nên tôi không biết cậu quản lý source kiểu gì nhưng về nguyên tắc là phải xây dựng hệ thống với các gói phụ thuộc, Ví dụ : Kode base tên Pascal và Lazarus  thì phải để Pascal ở chỗ Pascal, Lazarus ở chỗ Lazarus (bảo toàn code gốc 1 cách tối đa), mọi phần merge, patch, ... để riêng ---> những cái đó là của cậu và có thể soạn giấy phép riêng cho cậu luôn.
> 4. Rủi ro khi Pascal và Lararus thay đổi giấy phép thì Kode của cậu cũng tiêu luôn. Hãy chú ý điều đó.

+1

**Comment by tauitdnmd** [comment]
> Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> 

Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)

**Comment by quocthinhvo** [comment]
> > Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> 
> Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
> ![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)

@tauitdnmd cái đó được quyền làm vậy mà bác, em cũng có thể đổi lại. Nếu ngay từ đầu em muốn ăn cấp thì em đổi luôn mấy cái String đó rồi ạ.

**Comment by quocthinhvo** [comment]
> > Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> 
> Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
> ![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)

Cái đó không phải là đổi tên nha bác  @tauitdnmd . Em rebuild lại và thêm vào nhiều thứ lắm bác :v.

**Comment by tauitdnmd** [comment]
> > > Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> > 
> > 
> > Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
> > ![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)
> 
> @tauitdnmd cái đó được quyền làm vậy mà bác, em cũng có thể đổi lại. Nếu ngay từ đầu em muốn ăn cấp thì em đổi luôn mấy cái String đó rồi ạ.

Cậu đừng biện minh cho việc này. Cộng đồng opensource và giấy phép của Lazarus KO CHO PHÉP bất cứ ai xài mà đổi tên ( đánh mất credit của họ). Đã sai còn ko tiếp thu.

**Comment by quocthinhvo** [comment]
> > > > Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> > > 
> > > 
> > > Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
> > > ![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)
> > 
> > 
> > @tauitdnmd cái đó được quyền làm vậy mà bác, em cũng có thể đổi lại. Nếu ngay từ đầu em muốn ăn cấp thì em đổi luôn mấy cái String đó rồi ạ.
> 
> Cậu đừng biện minh cho việc này. Cộng đồng opensource và giấy phép của Lazarus KO CHO PHÉP bất cứ ai xài mà đổi tên ( đánh mất credit của họ). Đã sai còn ko tiếp thu.

Vâng em có thể sửa. Nhưng trong đó em có rebuild và thêm nhiều tính năng. Do em chưa up lên Github (vì nhiều nguyên nhân).

**Comment by quocthinhvo** [comment]
> > > > Thứ 6: trình biên dịch FPC và KC (Kode Compiler) trong Kode là 2 thứ khác biệt hoàn toàn. Kode dùng cả 2 cái trên. FPC dùng trong dịch thành mã máy (binary) còn KC dịch cho web. Em có đọc một bài trên Voz và mọi người bảo KC là FPC.exe em đổi tên? thật sự buồn vì điều này
> > > 
> > > 
> > > Thì chính xác cậu gọi tới kodepaskernel. Thực chất là file lazarus build đã bị đổi tên sang kodepaskernel. Đây là hành vi ăn cắp trắng trợn. Nếu cậu để nguyên file cuẩ lazarus thì mới đúng.
> > > ![1594793276501](https://user-images.githubusercontent.com/7830473/87746488-e67edc80-c81a-11ea-83ce-590645d767e1.png)
> > 
> > 
> > @tauitdnmd cái đó được quyền làm vậy mà bác, em cũng có thể đổi lại. Nếu ngay từ đầu em muốn ăn cấp thì em đổi luôn mấy cái String đó rồi ạ.
> 
> Cậu đừng biện minh cho việc này. Cộng đồng opensource và giấy phép của Lazarus KO CHO PHÉP bất cứ ai xài mà đổi tên ( đánh mất credit của họ). Đã sai còn ko tiếp thu.

Em chỉ muốn đóng góp cho cộng đồng và sẵn sàng sửa lại những yêu cầu của các bác @tauitdnmd .
Em cũng thêm nhiều thứ mới. Cái IDE Kode Studio là nó chạy online (kiểu cloud IDE). Còn KC là trình dịch chứ không phải fpc đổi tên như mọi người nghĩ :(((

**Comment by quocthinhvo** [comment]
@tauitdnmd Em sẽ sửa lại theo yêu cầu của bác. Vẫn phương châm trước đó là em làm vì cộng đồng. Em xin lỗi do chưa rõ mục đó trong giấy phép. Cảm ơn bác đã cho em thấy. Lần đầu làm project mở với lại phổ biến đến nhiều người nên đôi lúc lỡ lời khoe về Kode (em muốn thu hút mọi người hơn). Xem như đây là kinh nghiệm mà em có được từ mọi người.
Em sẽ vẫn tiếp tục làm Kode nhưng minh bạch hơn về LICENSE ạ. Một lần nữa cảm ơn bác bằng tất cả chân trọng 💯

**Comment by quocthinhvo** [comment]
@holao09  @tauitdnmd  hai bác có dùng Voz thì nói giúp em vài lời rằng em làm Kode cho cộng đồng và chỉ muốn mọi người ủng hộ. Em cảm ơn nhiều

**Comment by holao09** [comment]
> trường hợp 4 theo anh nhắc thì theo cách này có né được không ạ @holao09 

@quocthinhvo : nếu cậu đóng góp cho họ. Và những đóng góp đó được công nhận (merge vào source chung) chỉ 1 dòng thôi cũng được thì họ sẽ không thể cấm cậu sử dụng source code đó với giấy phép tại thời điểm phần source code của cậu đóng góp được merge vào.

Hãy đóng góp cho cộng đồng cậu sẽ có quyền sử dụng đồ của cộng đồng.

**Comment by quocthinhvo** [comment]
> 
> > trường hợp 4 theo anh nhắc thì theo cách này có né được không ạ @holao09 
> 
> @quocthinhvo : nếu cậu đóng góp cho họ. Và những đóng góp đó được công nhận (merge vào source chung) chỉ 1 dòng thôi cũng được thì họ sẽ không thể cấm cậu sử dụng source code đó với giấy phép tại thời điểm phần source code của cậu đóng góp được merge vào.
> 
> Hãy đóng góp cho cộng đồng cậu sẽ có quyền sử dụng đồ của cộng đồng.

Vâng ạ @holao09 

Nhưng em thắc mắc. Này em hỏi thật. Do kinh nghiệm về Open Source em còn ít.
1. em đã thêm trang license và ghi credit vào từng tệp và project em dùng lại. Và trang Credit em vừa tạo: https://kodelang.dev/license
2. Em còn không ổn chỗ nào. Anh có thể nói để em sửa.

**Comment by tranxuanthang** [comment]
> Cậu đừng biện minh cho việc này. Cộng đồng opensource và giấy phép của Lazarus KO CHO PHÉP bất cứ ai xài mà đổi tên ( đánh mất credit của họ). Đã sai còn ko tiếp thu.
@tauitdnmd
Theo mình hiểu thì giấy phép GPL đâu hề cấm việc đổi tên project/đổi tên file? Hơn nữa với thái độ của bác như này chỉ khiến doạ dẫm tác giả Kode và những người đến sau sợ hãi khỏi việc đóng góp cho cộng đồng open source thôi.

**Comment by quocthinhvo** [comment]
em xin phép đóng lại issue ạ
